add-note:
	node app.js add --title="Cyberpunk2077" --body="Lorem Ipsum"

add-note.validate:
	node app.js add

remove-note:
	node app.js remove --title="Cyberpunk2077"

lint:
	npm run lint

lint-watch:
	npx nodemon ./node_modules/eslint/bin/eslint.js -- ./ --fix
