add-file:
	npx nodemon app.js add --title="Cyberpunk2077" --body="Lorem Ipsum"

add-file.validate:
	npx nodemon app.js add

lint:
	npm run lint

lint-watch:
	./node_modules/nodemon/bin/nodemon.js ./node_modules/eslint/bin/eslint.js -- ./ --fix
