name: CI
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'
jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm run lint
